// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-07-07T04:41:07.190Z
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import ChatAppABI from './abi/ChatApp.json';
import ERC1967ProxyABI from './abi/ERC1967Proxy.json';

export const contracts = {
  ChatApp: {
    address: '0xdebd7482fc04282d6d3365608a83e1e1c6367e12' as const,
    deploymentTxHash: '0xbaced4dddee0903a33f39c0c6c6cd582d506db19a82b8bbd3c449b4b357c56c9',
    blockNumber: 0xfff569,
    abi: ChatAppABI
  },
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export specific contracts for convenience
export const CHATAPP_ADDRESS = '0xdebd7482fc04282d6d3365608a83e1e1c6367e12' as const;
export const CHATAPP_ABI = ChatAppABI;
