// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-07-07T04:41:07.191Z

import { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL } from '@/config/chain';

// Re-export for backward compatibility
export { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL };

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "ChatApp": "0xdebd7482fc04282d6d3365608a83e1e1c6367e12",
} as const;

// Re-export specific contract addresses
export const CHATAPP_ADDRESS = '0xdebd7482fc04282d6d3365608a83e1e1c6367e12' as const;
