// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-07-09T00:05:03.973Z

import { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL } from '@/config/chain';

// Re-export for backward compatibility
export { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL };

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "ChatApp": "0xccb0e49e0c09e2a40aca19f7eba6004faf370786",
  "ERC1967Proxy": "0xac10ec5135e3c6db04218be318cc603c85b765ce"
} as const;

// Re-export specific contract addresses
export const CHATAPP_ADDRESS = '0xccb0e49e0c09e2a40aca19f7eba6004faf370786' as const;
export const ERC1967PROXY_ADDRESS = '0xac10ec5135e3c6db04218be318cc603c85b765ce' as const;
